import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#052109",
        "primary": "#912219",
        "primary-fixed": "#ffdad5",
        "tertiary-container": "#006e7d",
        "inverse-primary": "#ffb4a9",
        "tertiary-fixed-dim": "#82d3e3",
        "inverse-surface": "#303032",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb4a9",
        "error": "#ba1a1a",
        "surface-bright": "#fcf8fb",
        "on-tertiary-fixed-variant": "#004e5a",
        "surface": "#fcf8fb",
        "surface-dim": "#dcd9dc",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#aecfaa",
        "on-primary-fixed": "#410001",
        "on-secondary-container": "#4e6c4d",
        "outline": "#8c716d",
        "on-primary": "#ffffff",
        "background": "#fcf8fb",
        "surface-container": "#f0edef",
        "on-error": "#ffffff",
        "surface-variant": "#e4e2e4",
        "on-secondary-fixed-variant": "#314d31",
        "tertiary-fixed": "#a1efff",
        "surface-container-highest": "#e4e2e4",
        "on-primary-container": "#ffd9d3",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#b23a2e",
        "secondary": "#486647",
        "on-tertiary-container": "#9deeff",
        "outline-variant": "#dfbfbb",
        "on-primary-fixed-variant": "#891c15",
        "secondary-fixed": "#caecc5",
        "inverse-on-surface": "#f3f0f2",
        "on-surface-variant": "#58413e",
        "on-background": "#1b1b1d",
        "surface-container-low": "#f6f3f5",
        "on-secondary": "#ffffff",
        "surface-tint": "#aa3529",
        "on-surface": "#1b1b1d",
        "tertiary": "#005460",
        "on-tertiary-fixed": "#001f25",
        "secondary-container": "#caecc5",
        "surface-container-high": "#eae7ea"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin": "3rem"
      },
      "fontFamily": {
        "stamp": ["Noto Serif"],
        "label-sm": ["Noto Sans"],
        "furigana": ["Noto Sans"],
        "headline-lg-mobile": ["Noto Serif"],
        "headline-lg": ["Noto Serif"],
        "kanji-display": ["Noto Serif"],
        "body-sm": ["Noto Sans"],
        "headline-sm": ["Noto Serif"],
        "display-lg-mobile": ["Noto Serif"],
        "body-lg": ["Noto Sans"],
        "body-md": ["Noto Sans"],
        "label-md": ["Noto Sans"],
        "display-lg": ["Noto Serif"],
        "headline-md": ["Noto Serif"]
      },
      "fontSize": {
        "stamp": ["0.8125rem", {"lineHeight": "1rem", "letterSpacing": "0.15em", "fontWeight": "700"}],
        "label-sm": ["0.75rem", {"lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "furigana": ["0.6875rem", {"lineHeight": "0.875rem", "letterSpacing": "0.04em", "fontWeight": "400"}],
        "headline-lg-mobile": ["1.5rem", {"lineHeight": "2rem", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-lg": ["2rem", {"lineHeight": "2.75rem", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "kanji-display": ["3rem", {"lineHeight": "3.5rem", "letterSpacing": "0.05em", "fontWeight": "400"}],
        "body-sm": ["0.8125rem", {"lineHeight": "1.375rem", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "headline-sm": ["1.125rem", {"lineHeight": "1.75rem", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg-mobile": ["2.25rem", {"lineHeight": "2.75rem", "letterSpacing": "0em", "fontWeight": "600"}],
        "body-lg": ["1.0625rem", {"lineHeight": "1.875rem", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "body-md": ["0.9375rem", {"lineHeight": "1.625rem", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "label-md": ["0.875rem", {"lineHeight": "1.25rem", "letterSpacing": "0.03em", "fontWeight": "500"}],
        "display-lg": ["3.5rem", {"lineHeight": "4.25rem", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["1.375rem", {"lineHeight": "2rem", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
};
export default config;
